using System;
namespace Hidistro.Entities.Sales
{
	public enum PurchaseOrderActions
	{
		DISTRIBUTOR_CLOSE = 1,
		DISTRIBUTOR_MODIFY_GIFTS,
		DISTRIBUTOR_CONFIRM_PAY,
		DISTRIBUTOR_CONFIRM_GOODS,
		MASTER__CLOSE,
		MASTER__MODIFY_AMOUNT,
		MASTER__MODIFY_SHIPPING_MODE,
		MASTER_MODIFY_DELIVER_ADDRESS,
		MASTER_SEND_GOODS,
		MASTER_REJECT_REFUND,
		MASTER_FINISH_TRADE,
		MASTER_CONFIRM_PAY
	}
}
