using System;
namespace Hidistro.Entities.Store
{
	public enum Privilege
	{
		Summary = 1000,
		SiteSettings,
		EmailSettings,
		SMSSettings,
		PaymentModes,
		ShippingModes,
		ShippingTemplets,
		ExpressComputerpes,
		MessageTemplets,
		PictureMange,
		Themes = 2001,
		Affiches,
		HelpCategories,
		Helps,
		ArticleCategories,
		Articles,
		FriendlyLinks,
		HotKeywords,
		Votes,
		Products = 3001,
		AddProducts,
		EditProducts,
		DeleteProducts,
		InStockProduct,
		UpShelfProducts,
		OffShelfProducts,
		PackProduct,
		UpPackProduct,
		ProductUnclassified,
		SubjectProducts,
		ProductBatchUpload,
		ProductLines,
		AddProductLine,
		EditProductLine,
		DeleteProductLine,
		ProductTypes,
		AddProductType,
		EditProductType,
		DeleteProductType,
		ProductCategory,
		AddProductCategory,
		EditProductCategory,
		DeleteProductCategory,
		BrandCategories,
		ProductBatchExport,
		Orders = 4001,
		DeleteOrder,
		EditOrders,
		CofimOrderPay,
		OrderSendGoods,
		ExpressPrint,
		RefundOrder,
		RemarkOrder,
		ExpressTemplates,
		Shippers,
		OrderLookup,
		OrderRefundApply,
		OrderReplaceApply,
		OrderReturnsApply,
		Members = 5001,
		EditMember,
		DeleteMember,
		MemberGrades,
		AddMemberGrade,
		EditMemberGrade,
		DeleteMemberGrade,
		OpenIdServices,
		OpenIdSettings,
		MemberBalanceStatistics,
		MemberDrawRequestStatistics,
		DistributorGrades = 6001,
		AddDistributorGrade,
		EditDistributorGrade,
		DeleteDistributorGrade,
		Distributor,
		EditDistributor,
		DeleteDistributor,
		DistributorRequests,
		DistributorRequestInstruction,
		ManageDistributorSites,
		DistributorSiteRequests,
		MakeProductsPack,
		TaobaoNote,
		DistributorSendedMsg,
		DistributorAcceptMsg,
		DistributorNewMsg,
		ProductConsultationsManage = 7001,
		ProductReviewsManage,
		ReceivedMessages,
		SendedMessages,
		AddMessage,
		ManageLeaveComments,
		ClientGroup,
		ClientNew,
		ClientActivy,
		ClientSleep,
		Gifts = 8001,
		ProductPromotion,
		OrderPromotion,
		BindProduct,
		GroupBuy,
		CountDown,
		Coupons,
		MemberAccount = 9001,
		MemberReCharge,
		BalanceDrawRequest,
		DistributorAccount,
		DistributorReCharge,
		DistributorBalanceDrawRequest,
		SaleReport = 10001,
		OrderStatistics,
		SaleDetails,
		SaleTargets,
		ProductSaleRanking,
		ProductSaleStatistics,
		MemberRanking,
		MemberArealDistributionStatistics,
		UserIncreaseStatistics,
		DistributionReport,
		PurchaseOrderStatistics,
		DistributionProductSaleRanking = 100112,
		DistributorAchievementsRanking,
		ManagePurchaseorder = 11001,
		EditPurchaseorder,
		DeletePurchaseorder,
		PurchaseorderSendGood,
		PurchaseorderRefund,
		PurchaseorderMark,
		PurchaseOrderRefundApply,
		PurchaseOrderReplaceApply,
		PurchaseOrderReturnsApply
	}
}
